### ISSUE TITLE
[MacOS] MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

### ISSUE THREAD

**Issue by GyuriMajercsik** [fluttercommunity/plus_plugins#214]
I would like to use a single package on all platforms (Android, iOS, MacOS, Web) for getting the app version. It seems that package_info_plus should support it.

Maybe I am doing something wrong or there is a bug in the package but I get the following: 

```
AsyncSnapshot<PackageInfo>(ConnectionState.done, null, MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info), #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
<asynchronous suspension>
#2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
<asynchronous suspension>
#3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:66:26)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart)
<asynchronous suspension>
)
```

**Comment by GyuriMajercsik** [comment]
As a temporary solution I used both packages: package_info and package_info_plus, in the following way:

```
import 'package:package_info/package_info.dart'
    if (dart.library.html) 'package:package_info_plus/package_info_plus.dart';

```

**Comment by miquelbeltran** [comment]
Hi @GyuriMajercsik why are you using `package_info` and `package_info_plus` at the same time? is there something that `package_info_plus` cannot do that `package_info` can? The issue to me seems that you are using `package_info` on MacOS instead of `package_info_plus`.

**Comment by GyuriMajercsik** [comment]
Hi @miquelbeltran , thanks for the quick response. 

It seems that `package_info_plus` doesn't work on MacOS, at least for me. I receive the above error.

**Comment by miquelbeltran** [comment]
Thanks for the clarification! The plugin works for me when I run the example on MacOS.

**Comment by GyuriMajercsik** [comment]
I tried in a test app and indeed, it is related to the fact that I have `package_info` as well in my dependencies. The problem is that I can't remove it because it is a transitive dependency.... 
I also noticed this error before the exception I already mentioned: 

```
objc[98243]: Class FLTPackageInfoPlugin is implemented in both 
/Users/gyuri/work/upwork/testing_project/build/macos/Build/Products/Debug/testing_project.app/Contents/Frameworks/package_info_plus_macos.framework/Versions/A/package_info_plus_macos (0x103364718) 
and /Users/gyuri/work/upwork/testing_project/build/macos/Build/Products/Debug/testing_project.app/Contents/Frameworks/package_info.framework/Versions/A/package_info (0x103353718). 
One of the two will be used. Which one is undefined.
```

I'm not sure if this is a bug but the exception is misleading.

**Comment by miquelbeltran** [comment]
I see! yes, the error is very relevant. Since package_info also has MacOS support there's a collision in the class name. The solution would be to rename the `FLTPackageInfoPlugin` class to `FLTPackageInfoPlusPlugin` in the `package_info_plus` project.

I currently don't have time to do the change, but a PR with the fix would be highly appreciate and I can help reviewing it.

**Comment by GyuriMajercsik** [comment]
@miquelbeltran , I created a pull request for this: https://github.com/fluttercommunity/plus_plugins/pull/215

**Comment by GyuriMajercsik** [comment]
The issue was fixed, merged and released. Closing.

**Comment by pinkasey** [comment]
I'm still getting this in package_info_plus: `1.3.0`, when I run widfet-tests:
```
00:06 +1 -4: /Users/eyalpinkas/Projects/challenge22app/test/lang_ext/utils_test.dart: isLink [E]                                            
  MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
  package:flutter/src/services/platform_channel.dart 154:7  MethodChannel._invokeMethod
```

I've checked in `FLTPackageInfoPlusPlugin.h` in the package's source - 
I see:
```
@interface FLTPackageInfoPlusPlugin : NSObject <FlutterPlugin>
```
So I believe I have the fix in @GyuriMajercsik 's PR.
Also, I've checked my `pubspec.lock` - I don't have a dependency on `package_info` (not even transitive).

flutter doctor:
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter
Framework • revision 18116933e7 (2 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-IL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
[✓] VS Code (version 1.58.2)

```

help?

**Comment by Devenom1** [comment]
The same issue that @pinkasey mentioned happened with me too. After trying multiple options like re-building the app and re-opening the emulator it started working. I'm running it on MacOS too. This should be looked into at some point

**Comment by tripbnb66** [comment]
This problem is still there and below is the result of flutter doctor.
`

[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hant-TW)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Brave Browser.app/Contents/MacOS/Brave Browser)
    ! /Applications/Brave Browser.app/Contents/MacOS/Brave Browser is not executable.
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.64.1)
[✓] Connected device (2 available)

`

I fixed it with a temporary solution.
I suggested to reopen this bug  and dig this problem again.
Thank you.

`
PackageInfo? packageInfo;
  var appVersion = '';
  var appBuildNumber = '';

@override
  void initState() {
    super.initState();
    getPackage();
  }

void getPackage() async {
    try {
      packageInfo = await PackageInfo.fromPlatform();
      appVersion = packageInfo!.version;
      appBuildNumber = packageInfo!.buildNumber;
    } catch (e, stack) {
      print(e);
      print(stack);
    }
  }

(appVersion == '' ? Text('') : Text(appVersion + '+' + appBuildNumber)),

`

**Comment by Areopagitics** [comment]
windows has the same issue as well... I opened another issue for it #760

**Comment by kerberjg** [comment]
Still an issue on macOS, but only when running unit tests (regardless of whether `TestWidgetsFlutterBinding/WidgetsFlutterBinding.ensureInitialized` is called)

```
  MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)
  package:flutter/src/services/platform_channel.dart 332:7  MethodChannel._invokeMethod
```

**Comment by miquelbeltran** [comment]
Hi @kerberjg Is there a reason you calling to a platform plugin from a unit test? The general recommendation with 3rd party code is that you mock or fake that dependency.

**Comment by chadpav** [comment]
This is a closed issue but I was hitting this error while trying to run a unit test since there isn't a platform. I resolved it by calling the 'setMockValues' method. This will create a "testPlatform" instance while the test is running.

```
PackageInfo.setMockInitialValues(
        appName: 'appName',
        packageName: 'packageName',
        version: '1.0',
        buildNumber: '1',
        buildSignature: 'buildSignature',
      );
```

**Comment by miquelbeltran** [comment]
Those methods are intended for internal testing, of course, we are not going to block anyone from using them. That's why it is annotated with `visibleForTesting`.

A better approach would be to re-write the plugin as an instanciable class rather than exposing static methods, so you can create your own mocks.

Nevertheless, my recommendation still is for you to wrap the plugin access with a class you can replace via dependency injection.
